### ISSUE TITLE
3.17 support for gitlab-foss

### ISSUE THREAD

**Issue by ayakael** [jirutka/user-aports#1]
I've been maintaining your gitlab-foss aport on my personal user-aports [here](https://lab.ilot.io/ayakael/user-aports/-/tree/v3.17). I've just now figured out how to update to ruby 3.1, thus supporting openssl3 and alpine 3.17. You're free to update your own, or use my own build artifacts available in these repos:

https://lab.ilot.io/ayakael/repo-apk/-/raw/v3.17/user
https://lab.ilot.io/ayakael/repo-apk/-/raw/v3.17/backports

So far, no issues have surfaced since upgrading.

**Comment by ayakael** [comment]
There are still issues with libgit2, so rugged runs its own bundled version for now.

**Comment by ayakael** [comment]
Fixed the libgit2 issue by using your ruby-rugged aports directly.

**Comment by jirutka** [comment]
Thanks for letting me know, it makes me happy to know that my GitLab aports didn’t go to waste and someone else is developing it. I’m no longer running a GitLab instance, so I won’t be maintaining this aport anymore.

I wonder how long you’ll be able to keep it up, as GitLab has become an insanely complex mess and updating the aports is becoming increasingly depressing (digging in that mess) and time-consuming. I almost gave up on the last upgrade, but running it in a container (just for the upgrade process of an old instance) turned out to be slow and clumsy as hell. I wish you strong nerves!

**Comment by ayakael** [comment]
Thanks for your wishes! It hasn't been terrible! There were a few hickups along the way, and always having to keep ruby3.0 up to date is a bit of a hassle, but my distaste for docker is strong! I would like to eventually move to another Git platform, but GitLab is serving me well right now.

Edit: Not to mention, GitLab sends out an upgrade really often, and resulting APKg are massive!
